<div class="ambassador_nav">
<ul >
         <li ><a href="<?php echo $this->getBaseUrl();?>ambassador/" title="Distributor Control Panel" ><?php echo $this->__('View Group Member') ?></a></li>
         <li ><a href="<?php echo $this->getBaseUrl();?>ambassador/index/viewgroupbv/" title="Distributor view group sale" ><?php echo $this->__('View Group Sale (BV)') ?></a></li>
         <li ><a href="<?php echo $this->getBaseUrl();?>ambassador/index/viewgroupgl/" title="Distributor view group EL" ><?php echo $this->__('View Group EL') ?></a></li>
 </ul>
</div>