<?php 
$item_name = $this->getCustomerName();
$id = $this->getRequest()->getParam('id');
$username = $this->getRequest()->getParam('username');
$store = Mage::app()->getStore(1);
$curency_code = (string)$store->getBaseCurrencyCode();
$amount= Mage::getStoreConfig('admin/vipcustomer/upgradeamount');
?>
<div align="center" >
<h1 style="font-family:Arial, Helvetica, sans-serif; font-size:18px; letter-spacing: 0.1em; color:#0033CC;">If the page does not redirect you in a few moments, you can click on the button to continue</h1>
<form action="<?php echo Mage::getModel('paypal/standard')->getPaypalUrl()?>" method="post" name="myform">
		<input type="hidden" name="cmd" value="_xclick">
		<input type="hidden" name="business" value="<?php echo Mage::getStoreConfig('paypal/wps/business_account')?>">
		<input type="hidden" name="invoice" value="<?php echo $id ?>-<?php echo $username?>">
		<input type="hidden" name="item_name" value="<?php echo $item_name ?>">
		<input type="hidden" name="item_number" value="1">
		<input type="hidden" name="amount" value="<?php echo $amount ?>">
		<input id="address_override" name="address_override" value="1" type="hidden"/>
		<input id="first_name" name="first_name" value="<?php echo $this->getCustomer()->getFirstname()?>" type="hidden"/>
		<input id="last_name" name="last_name" value="<?php echo $this->getCustomer()->getLastname()?>" type="hidden"/>
		<input type="hidden" name="no_shipping" value="0">
		<input type="hidden" name="return" value="<?php echo $this->getUrl('customer/account/upgradesuccess')?>">
		<input type="hidden" name="notify_url" value="<?php echo $this->getUrl('customer/account/upgradecancel')?>">
		<input type="hidden" name="no_note" value="1">
		<input type="hidden" name="custom" value="haha">
		<input type="hidden" name="currency_code" value="<?php echo $curency_code?>">
		<input type="hidden" name="lc" value="US">
		<input type="hidden" name="bn" value="PP-BuyNowBF">
		<br /><br />
		<input type="submit" value="Click Here to Pay via Paypal">

		<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" onload="document.myform.submit()" />
		</form>
		</div>
<script language="javascript"><!--
		//document.myform.submit()
		//onload="document.myform.submit()"
		//-->
		</script>

