SET FOREIGN_KEY_CHECKS=0;
 
TRUNCATE `usez_sales_order`;
TRUNCATE `usez_sales_order_datetime`;
TRUNCATE `usez_sales_order_decimal`;
TRUNCATE `usez_sales_order_entity`;
TRUNCATE `usez_sales_order_entity_datetime`;
TRUNCATE `usez_sales_order_entity_decimal`;
TRUNCATE `usez_sales_order_entity_int`;
TRUNCATE `usez_sales_order_entity_text`;
TRUNCATE `usez_sales_order_entity_varchar`;
TRUNCATE `usez_sales_order_int`;
TRUNCATE `usez_sales_order_text`;
TRUNCATE `usez_sales_order_varchar`;
TRUNCATE `usez_sales_flat_quote`;
TRUNCATE `usez_sales_flat_quote_address`;
TRUNCATE `usez_sales_flat_quote_address_item`;
TRUNCATE `usez_sales_flat_quote_item`;
TRUNCATE `usez_sales_flat_quote_item_option`;
TRUNCATE `usez_sales_flat_order_item`;
TRUNCATE `usez_sendfriend_log`;
TRUNCATE `usez_tag`;
TRUNCATE `usez_tag_relation`;
TRUNCATE `usez_tag_summary`;
TRUNCATE `usez_wishlist`;
TRUNCATE `usez_log_quote`;
TRUNCATE `usez_report_event`;
TRUNCATE `usez_affiliatebv`;
TRUNCATE `usez_affiliatecommission`;
TRUNCATE `usez_company_distribute`;
TRUNCATE `usez_company_pool`;
TRUNCATE `usez_groupbv`;
TRUNCATE `usez_groupgl`;
TRUNCATE `usez_groupglused`;
TRUNCATE `usez_groupsales`;
TRUNCATE `usez_orphan_distribute`;
TRUNCATE `usez_orphan_pool`;
TRUNCATE `usez_commissions`;
 
ALTER TABLE `usez_sales_order` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_order_datetime` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_order_decimal` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_order_entity` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_order_entity_datetime` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_order_entity_decimal` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_order_entity_int` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_order_entity_text` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_order_entity_varchar` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_order_int` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_order_text` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_order_varchar` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_flat_quote` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_flat_quote_address` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_flat_quote_address_item` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_flat_quote_item` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_flat_quote_item_option` AUTO_INCREMENT=1;
ALTER TABLE `usez_sales_flat_order_item` AUTO_INCREMENT=1;
ALTER TABLE `usez_sendfriend_log` AUTO_INCREMENT=1;
ALTER TABLE `usez_tag` AUTO_INCREMENT=1;
ALTER TABLE `usez_tag_relation` AUTO_INCREMENT=1;
ALTER TABLE `usez_tag_summary` AUTO_INCREMENT=1;
ALTER TABLE `usez_wishlist` AUTO_INCREMENT=1;
ALTER TABLE `usez_log_quote` AUTO_INCREMENT=1;
ALTER TABLE `usez_report_event` AUTO_INCREMENT=1;
 
-- reset customers
TRUNCATE `usez_customer_address_entity`;
TRUNCATE `usez_customer_address_entity_datetime`;
TRUNCATE `usez_customer_address_entity_decimal`;
TRUNCATE `usez_customer_address_entity_int`;
TRUNCATE `usez_customer_address_entity_text`;
TRUNCATE `usez_customer_address_entity_varchar`;
TRUNCATE `usez_customer_entity`;
TRUNCATE `usez_customer_entity_datetime`;
TRUNCATE `usez_customer_entity_decimal`;
TRUNCATE `usez_customer_entity_int`;
TRUNCATE `usez_customer_entity_text`;
TRUNCATE `usez_customer_entity_varchar`;
TRUNCATE `usez_log_customer`;
TRUNCATE `usez_log_visitor`;
TRUNCATE `usez_log_visitor_info`;
 
ALTER TABLE `usez_customer_address_entity` AUTO_INCREMENT=1;
ALTER TABLE `usez_customer_address_entity_datetime` AUTO_INCREMENT=1;
ALTER TABLE `usez_customer_address_entity_decimal` AUTO_INCREMENT=1;
ALTER TABLE `usez_customer_address_entity_int` AUTO_INCREMENT=1;
ALTER TABLE `usez_customer_address_entity_text` AUTO_INCREMENT=1;
ALTER TABLE `usez_customer_address_entity_varchar` AUTO_INCREMENT=1;
ALTER TABLE `usez_customer_entity` AUTO_INCREMENT=1;
ALTER TABLE `usez_customer_entity_datetime` AUTO_INCREMENT=1;
ALTER TABLE `usez_customer_entity_decimal` AUTO_INCREMENT=1;
ALTER TABLE `usez_customer_entity_int` AUTO_INCREMENT=1;
ALTER TABLE `usez_customer_entity_text` AUTO_INCREMENT=1;
ALTER TABLE `usez_customer_entity_varchar` AUTO_INCREMENT=1;
ALTER TABLE `usez_log_customer` AUTO_INCREMENT=1;
ALTER TABLE `usez_log_visitor` AUTO_INCREMENT=1;
ALTER TABLE `usez_log_visitor_info` AUTO_INCREMENT=1;
 
-- Reset all ID counters
TRUNCATE `usez_eav_entity_store`;
ALTER TABLE  `usez_eav_entity_store` AUTO_INCREMENT=1;
 
SET FOREIGN_KEY_CHECKS=1;