<div class="page-head">
    <h3><?php echo $this->__('Upgrade to Ambassador') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/upgradePost') ?>" method="post" id="form-validate">
<fieldset class="group-select">
    <?php echo $this->getBlockHtml('formkey')?>
    <h4 class="legend"><?php echo $this->__('Account Information') ?></h4>
    <ul>
        <li>
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
       </li>
       <li>
            <div class="input-box">
            <label for="username"><?php echo $this->__('Ambassador Username') ?> <span class="required">*</span></label><br />
            <input type="text" name="username" id="username" value="<?php echo $this->htmlEscape($this->getCustomer()->getUsername()) ?>" title="<?php echo $this->__('Ambassador Username') ?>" class="required-entry input-text" />
            </div>
        </li>
        <li>
            <div class="input-box">
            <label for="email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
            <input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="required-entry validate-email input-text" />
            </div>
        </li>
<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
<?php if ($_dob->isEnabled()): ?>
        <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
<?php endif ?>
<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
<?php if ($_taxvat->isEnabled()): ?>
        <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
<?php endif ?>
		<li>
			<input type="checkbox" id="term_condition_upgrade_agree" /> <a href="javascript:viewterm();">Nhung quyen loi va quy dinh khi dang ky</a>
		</li>
    </ul>
</fieldset>
<fieldset class="group-select" id="term_condition_upgrade" style="display: none">
<div >
Nhung dieu kien can phai dua vao Chuahoanthien
</div>
</fieldset>
<div class="button-set">
    <a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <button type="submit" class="form-button"><span><?php echo $this->__('Save') ?></span></button>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
	function viewterm()
	{
		if( document.getElementById('term_condition_upgrade').style.display == 'none')
			document.getElementById('term_condition_upgrade').style.display = 'block';
		else
			document.getElementById('term_condition_upgrade').style.display = 'none';
	}
		   
//]]>
</script>