<ul class="messages">
	    <li class="success-msg">
		    <ul>
		    <li>Your Redemption Product Order has been succeed.</li>
		    <li>We will ship your order items to Address you provide in your user account. If have any diffrent, please contact us for change.</li>
		    
		    </ul>
	    </li>
    </ul>
 <div class="button-set">
    <button type="button" class="form-button" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><?php echo $this->__('Continue Shopping') ?></span></button>
</div>