<!--Main content-->

           
            <div id="wrapper_left">

	      <br/>
	   <ol>
       	<li><strong>Member</strong>-  As a Member, instead of buying from retail shops, you simply purchase the same product or sign up for the same services from USEZ online. You accumulate loyalty points (on any amount spent), and exchange the points for free products.<br/>
        <a href="<?php echo $this->getUrl('customer/account/login')?>"><img src="<?php echo $this->getSkinUrl('images/joinnow2.jpg')?>" border="0" align="right" /></a><br/><br/><br class="clr"/></li>
        <li><strong>Distributor</strong>-  As a Distributor , you enjoy all the benefits of the Member. Additionally, you can refer friends to sign up as Member. USEZ will track your friends purchases and send you a commission cheque every month.</li>
        <br />

        <a href="<?php echo $this->getUrl('customer/account/login')?>"><img src="<?php echo $this->getSkinUrl('images/joinnow.jpg')?>" border="0" align="right" /></a>
       </ol>
                
               
            </div>
	                <div id="wrapper_right">
            <table width="95%">
            <tr>
            <td width="40%" rowspan="2">
            <img src="<?php echo $this->getSkinUrl('images/affiliate.jpg')?>" border="0" align="right" /></td>
            <td>If you are in business selling products and services relating to health, wellness and personal grooming, and you want to expand your sales on the Internet, but do not have the resources to launch your own Internet marketing campaign, then consider joining USEZ as an Affiliate Partner. <br/>

<br/>
USEZ will take care of all the marketing. And you will reach out to more than 100,000 customers instantly.</td>
            </tr>
            <tr><td colspan="2"><br/><a href="<?php echo $this->getUrl('customer/account/create')?>"><img src="<?php echo $this->getSkinUrl('images/joinnow.jpg')?>" border="0" align="right" /></a></td></tr>
            </table>
               
	                <!--End main content-->
            <div class="clr"></div>
        </div>
        <div class="clr"></div>

        <div style="padding:20px; font-size:13px; font-weight:bold;">To enquire about the Affiliate Partner programme, please contact XXXXXX.</div>
        <div class="clr"></div>
	

           