
<div id="banner" style="height:380px;">
<script language="javascript1.2" type="text/javascript" src="<?php echo $this->getSkinUrl('js/fadein-out.js') ?>"></script> 
<script type="text/javascript"> 
//new fadeshow(IMAGES_ARRAY_NAME, slideshow_width, slideshow_height, borderwidth, delay, pause (0=no, 1=yes), optionalRandomOrder)
new fadeshow(fadeimages, 900, 380, 0, 3000, 1, "R") 
</script>
 </div>
 
