<div class="ambassador_nav">
<ul >
         <li ><a href="<?php echo $this->getBaseUrl();?>ambassador/" title="Ambassador Control Panel" >View Group Member</a></li>
         <li ><a href="<?php echo $this->getBaseUrl();?>ambassador/index/viewgroupbv/" title="Ambassador view group sale" >View Group Sale</a></li>
         <li ><a href="<?php echo $this->getBaseUrl();?>ambassador/index/viewgroupgl/" title="Ambassador view group EL" >View Group EL</a></li>
 </ul>
</div>